version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: task-manager-bot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: java-app
    depends_on:
      - vault
      - mongo
    ports:
      - "8080:8080"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: task-manager-bot

volumes:
  mongodb_data:
