version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev
    restart: unless-stopped
    healthcheck:
      test: vault -v
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tm_user
      MONGO_INITDB_ROOT_PASSWORD: tm_pass
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --quiet --eval "db.adminCommand('ping')" || exit 1
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: unless-stopped

  app:
    build: .
    container_name: java-app
    depends_on:
      mongo:
        condition: service_healthy
      vault:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN_FILE: /run/secrets/vault_root_token
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - vault_root_token

secrets:
  vault_root_token:
    file: vault_root_token.txt

volumes:
  mongodb_data:
