version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
        test: mongosh --quiet --eval "db.adminCommand('ping')" || exit 1
        interval: 5s
        retries: 5
        start_period: 10s
        timeout: 10s

  app:
    build: .
    container_name: java-app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
