# Параметры Heat для окружения студента. При необходимости скорректируйте subnet UUID в Horizon.
parameters:
  image_id: "16729277-5d18-44ce-9581-1b2fd5d5659a"
  flavor_id: "m1.small"
  key_name: "astafyev-key"
  existing_subnet_id: "87af7ae7-714d-4472-b19a-7a4ec8505165"
  security_groups: "astafyev-sg"
  availability_zone: "nova"
